# Generated by Django 3.0.7 on 2020-06-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=255)),
                ('transaction_property', models.CharField(max_length=255)),
                ('transaction_property_datatype', models.CharField(default='number', max_length=255)),
            ],
        ),
    ]
