# Generated by Django 3.0.7 on 2020-06-06 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_property', models.CharField(max_length=255)),
                ('transaction_value', models.IntegerField()),
                ('user_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to='statements.UserTransaction')),
            ],
        ),
    ]
