# Generated by Django 3.0.7 on 2020-06-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_usertransactiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.CharField(max_length=255)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement', to='statements.Statement')),
            ],
        ),
    ]
