# Generated by Django 3.0.7 on 2020-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0004_statement_statementdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementdetail',
            name='line_item_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
